### ISSUE TITLE
Breaks Sourcemaps?

### ISSUE THREAD

**Issue by robneu** [cedaro/grunt-wp-css#12]
I've been working on getting source maps working for our theme and plugin configs and i think I've manged to trace the issue back to this module.

Has anyone else run into issues with source maps being inaccurate/broken after the file is run through grunt-wp-css?

**Comment by bradyvercher** [comment]
I haven't looked into sourcemaps myself, but since this is a light wrapper around CSScomb, you might make sure that project supports sourcemaps first.

**Comment by robneu** [comment]
I'm pretty sure it does, or at least newer versions of it does. Is it possible to pass options directly to CSScomb?

**Comment by bradyvercher** [comment]
Yeah, it'll pick up any custom options in a [`.csscomb.json` file in your project root](https://github.com/cedaro/grunt-wp-css/blob/6386213d99910ca719b741c0e35c6c33bff3ce5f/tasks/wpcss.js#L40). It might also be possible to [specify overrides directly in the task config](https://github.com/cedaro/grunt-wp-css/blob/6386213d99910ca719b741c0e35c6c33bff3ce5f/tasks/wpcss.js#L44).

The CSS is also run through CSS Beautify and a few manual comment clean up tasks, so I imagine any one of those could potentially break sourcemaps.

**Comment by robneu** [comment]
After digging into this a bit, it seems like CSSComb might just be incompatible with source maps. I think the issue is that the map expects things to be on certain lines and once the code has been processed those lines have shifted and the map no longer syncs up.

Both CSScomb and the line break processing break source maps, so it seems like this is what's going on. Since the map is generated when the Sass is built and then handled by a few modules that are run after it, I'm not sure if it'll be possible to get this working.

**Comment by bradyvercher** [comment]
Bummer, I figured something like that might be the case. I'm going to close this out since it would need to be resolved in CSScomb, but I'll keep an eye on upcoming releases in case it's possible to fix in the future.
